# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enviro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaspPi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaspPiChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_input', models.BooleanField(default=True)),
                ('serial_num', models.IntegerField()),
                ('input_string', models.CharField(max_length=256)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propygate_core.RaspPi')),
            ],
        ),
        migrations.CreateModel(
            name='RelayController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plug', models.IntegerField(unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propygate_core.RaspPiChannel', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempProbe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('serial_num', models.CharField(max_length=16)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propygate_core.RaspPiChannel')),
            ],
        ),
        migrations.CreateModel(
            name='TempProbeChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_changed', models.DateTimeField()),
                ('measurement_frequency', models.PositiveSmallIntegerField()),
                ('temp_ideal', models.DecimalField(decimal_places=1, max_digits=3)),
                ('temp_low_low', models.DecimalField(decimal_places=1, max_digits=3)),
                ('temp_low', models.DecimalField(decimal_places=1, max_digits=3)),
                ('temp_high', models.DecimalField(decimal_places=1, max_digits=3)),
                ('temp_high_high', models.DecimalField(decimal_places=1, max_digits=3)),
                ('enviro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propygate_core.Enviro')),
            ],
            options={
                'ordering': ['datetime_changed'],
                'get_latest_by': 'datetime_changed',
            },
        ),
        migrations.CreateModel(
            name='TempRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=3)),
                ('enviro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propygate_core.Enviro')),
            ],
            options={
                'get_latest_by': 'id',
            },
        ),
        migrations.AddField(
            model_name='enviro',
            name='heater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enviro_heater', to='propygate_core.RelayController'),
        ),
        migrations.AddField(
            model_name='enviro',
            name='light',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enviro_light', to='propygate_core.RelayController'),
        ),
        migrations.AddField(
            model_name='enviro',
            name='temp_probe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='propygate_core.TempProbe'),
        ),
        migrations.AddField(
            model_name='enviro',
            name='temp_probe_change_current',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enviro_temp_probe_current', to='propygate_core.TempProbeChange'),
        ),
    ]
