# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propygate_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rasppichannel',
            old_name='serial_num',
            new_name='channel_num',
        ),
    ]
