# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propygate_core', '0002_auto_20170203_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasppichannel',
            name='input_string',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
