# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propygate_core', '0003_auto_20170203_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relaycontroller',
            name='plug',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
