# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propygate_core', '0007_auto_20170203_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayControllerToggle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_toggled', models.DateTimeField()),
                ('is_on', models.BooleanField(default=False)),
                ('enviro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propygate_core.Enviro')),
            ],
            options={
                'get_latest_by': 'datetime_toggled',
            },
        ),
        migrations.AlterModelOptions(
            name='ideals',
            options={'get_latest_by': 'datetime_changed', 'ordering': ['datetime_changed'], 'verbose_name_plural': 'Ideals'},
        ),
        migrations.AlterModelOptions(
            name='temprecord',
            options={'get_latest_by': 'datetime_recorded'},
        ),
        migrations.AddField(
            model_name='temprecord',
            name='datetime_recorded',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
