# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propygate_core', '0009_auto_20170203_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasppichannel',
            name='is_low',
            field=models.BooleanField(default=True),
        ),
    ]
