# Generated by Django 3.1.7 on 2021-04-01 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propygate_core', '0011_auto_20170220_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relaycontrollertoggle',
            options={'get_latest_by': 'datetime_toggled', 'ordering': ['-datetime_toggled']},
        ),
        migrations.AddField(
            model_name='enviro',
            name='fan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enviro_fan', to='propygate_core.relaycontroller'),
        ),
    ]
