# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enviro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviro',
            name='temp_probe_change_current',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enviro_temp_probe_current', to='enviro.TempProbeChange'),
        ),
    ]
