# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviro', '0002_enviro_temp_probe_change_current'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temprecord',
            options={'get_latest_by': 'id'},
        ),
        migrations.AddField(
            model_name='enviro',
            name='name',
            field=models.CharField(default='Name', max_length=32),
            preserve_default=False,
        ),
    ]
