# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviro', '0003_auto_20170123_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tempprobechange',
            options={'ordering': ['datetime_changed']},
        ),
        migrations.AddField(
            model_name='tempprobe',
            name='serial_num',
            field=models.CharField(default='tempserial', max_length=16),
            preserve_default=False,
        ),
    ]
